# Generated by Django 4.2.3 on 2023-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/pasedon.jpg', upload_to='users/'),
        ),
    ]
